### PR TITLE
Enhancements - ability to filter LDAP results, tolerate different LDAP user fields

### PR DESCRIPTION
**Pull request by ghost**
A couple of changes required to make this work for my use case.

### CODE REVIEW

**Comment by pmuller** [comment]
Hello rodom!

Thanks for contributing.

I wrote this when _trying_ to use Rundeck, but since then I moved toward another scheduler, so I will certainly never reuse this project. If you are interested, you can takeover the project on your side and I can redirect people to your repository.

About contributions: as I have no test, it's hard to predict if things will break or not. And I am sorry for this!

Reading f05a36989692d59ed77d279eba1b187be68e5965 I am comfortable to merge it.
But I am not as confortable with 23e6424900ebe9f02589e0c5f62e21cb894f7621 as I have no idea of the result of the big one liners.

So, do you want to take over the project and be fully free on your side? ;-)

**Comment by ghost** [comment]
Hi!

I can take over if you wish - it looks like we'll be using Rundeck for the foreseeable future, so at least I have ability to test (not much spare time, but as this is the first PR it doesn't look like it'll be particularly demanding!).

23e6424 isn't perfect, but is better than the current behaviour if the LDAP directory doesn't have those attributes. It simply uses an empty string if the "mail" attribute is missing, and attempts to split "cn" (commonName) on spaces to get a first/last name if "givenName" or "sn" aren't present.

Naturally both changes are tested and work for me :-)

**Comment by pmuller** [comment]
OK, works for me!
I'll merge this PR then add a commit pointing new users to your repository.
Have fun :)

**Comment by ghost** [comment]
Thanks :-)

**Pull request merged**
